Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Naming/FileName:
  Enabled: false
  
Naming/MethodParameterName:
  MinNameLength: 1

Layout/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 40
  